mateapp-crm/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('search/', views.search, name='search'),
    path('login/', views.login, name='login'),
    path('signout/', views.signout, name='Logout'),
    path('user_trash/<int:a>/<int:b>/', views.user_trash, name='User_Trash'),
    path('admin_trash/<int:a>/<int:b>/', views.admin_trash, name='Admin_Trash'),
    path('admin_home/<int:a>/<int:b>/', views.admin_home, name='Admin_Home'),
    path('backup/', views.do_backup, name='Backup'),
]

mateapp-crm/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name = 'Register'),
    path('profile/', views.profileView , name = 'profileView'),
    path('change_password/', views.passwordChange, name = 'passwordChange'),
    path('profile_edit/', views.profileEdit , name = 'profileEdit'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('password_reset/', views.passwordResetRequest, name = 'passwordReset'),
    path('password_reset_confirm/<uidb64>/<token>/', views.passwordResetConfirm, name='passwordResetConfirm'),
    path('inactive_users/<int:a>/<int:b>/', views.inactive_users, name = 'inactiveUsers'),
    path('user/<int:id>/', views.user, name='User'),
    path('create_user/', views.create_user, name = 'createUser'),
    path('edit_user/<int:id>', views.edit_user, name = 'editUser'),
]

mateapp-crm/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from .validators import validate_email_domain
from .managers import CustomUserManager


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True, validators=[validate_email_domain])
    role = models.CharField(max_length=15, default='User', blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

mateapp-crm/users/forms.py
from typing import Any, Mapping, Optional, Type, Union
from django import forms
from django.forms.utils import ErrorList
from django.forms.widgets import Widget, TextInput, PasswordInput
from django.contrib.auth import login as auth_login, logout, authenticate, get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm
from .models import CustomUser
from django.utils.translation import gettext_lazy as _

ROLE_CHOICES = [
    ("User", _("User")),
    ("Administrator", _("Administrator")),
]

class CustomUserCreationForm(UserCreationForm):

    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'password'}),
    )
    password2 = forms.CharField(
        label=_("Confirm password"),
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'password'}),
    )

    role = forms.ChoiceField(
        choices=ROLE_CHOICES
    )

    role.widget.attrs.update({'class' : 'form-select'})

    class Meta:
        model = CustomUser
        fields = [
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
            "is_active",
            "is_staff",
            "role",
            ]

        widgets = {
            'email': forms.EmailInput(attrs={'class':'form-control','placeholder':'email'}),
            'first_name' : forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}),
            'last_name': forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}),
            'is_staff' : forms.CheckboxInput(attrs={'class':'form-check-input'}),
            'is_active' : forms.CheckboxInput(attrs={'class':'form-check-input'}),
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['role'].required = False


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = [
            "first_name",
            "last_name",
            ]
        
        widgets = {
            'first_name' : forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}),
            'last_name': forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}),
        }

class CustomUserEditForm(UserChangeForm):

    role = forms.ChoiceField(
        choices=ROLE_CHOICES
    )

    role.widget.attrs.update({'class' : 'form-select'})

    class Meta:
        model = CustomUser
        fields = [
            "first_name",
            "last_name",
            "is_active",
            "is_staff",
            "role",
            ]
        
        widgets = {
            'first_name' : forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}),
            'last_name': forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}),
            'is_staff' : forms.CheckboxInput(attrs={'class':'form-check-input'}),
            'is_active' : forms.CheckboxInput(attrs={'class':'form-check-input'}),
        }

class ChangePasswordForm(UserCreationForm):

    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'password'}),
    )
    password2 = forms.CharField(
        label=_("Confirm password"),
        widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'placeholder':'password'}),
    )

    class Meta:
        model = CustomUser
        fields = [
            'password1',
            'password2',
        ]

class PasswordResetForm(forms.Form):

    email = forms.EmailField(
        label=_("eMail"),
        widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'email'}),
    )

mateapp-crm/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, response, request
from .forms import CustomUserCreationForm, CustomUserChangeForm, ChangePasswordForm, PasswordResetForm, CustomUserEditForm
from main.decorators import user_not_authenticated, allowed_users, self_registration_enabled
from main.functions import paginator
from django.contrib import messages
from django.contrib.auth import login as auth_login, logout, authenticate, get_user_model
from django.contrib.auth.decorators import login_required
from django.template import loader
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from .tokens import account_activation_token
from django.db.models.query_utils import Q
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from .functions import checkUserActivationLimit, checkUserCreationLimit


# Create your views here.

# Activate

def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        if settings.REGISTRATION_PARKING == False:
            activeEnabled = checkUserCreationLimit()
            if activeEnabled:
                user.is_active = True
                user.save()
                messages.success(request, _('Thank you for your confirmation. Your account is now active'))
                return redirect('/login/')
            else:
                user.is_active = False
                user.save()
                messages.success(request, _('Thank you for your confirmation. The Administrator will enable your account soon.'))
                return redirect('/login/')
        else:
            user.is_active = False
            user.save()
            messages.success(request, _('Thank you for your confirmation. The Administrator will enable your account soon.'))
            return redirect('/login/')
    else:
        messages.error(request, _("Activation link is invalid. Contact the administrator"))
    return redirect('/login/')

# Sends Activation Email

def activationEmail(request, user, to_email):
    mail_subject = _('Activate your user account.')
    message = render_to_string('users/activate_account.html', {
        'user': user.first_name,
        'domain': get_current_site(request).domain,
        'uid' : urlsafe_base64_encode(force_bytes(user.pk)),
        'token' : account_activation_token.make_token(user),
        'protocol' : 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    try:
        email.send()
        messages.success(request, _('Please go to your email inbox and click on the included activation link to enable your account. <b>Note:</b> Remember to check your spam folder.'))
    except:
        user.delete()
        messages.error(request, _('There was a problem sending the email. Please contact the Administrator'))    

# Handles registration form.

@user_not_authenticated
@self_registration_enabled
def register(request):
    registerform = CustomUserCreationForm(request.POST)
    mdomain = settings.REGISTRATION_DOMAIN
    if request.method == 'POST':  
        if registerform.is_valid():
            user = registerform.save(commit=False)
            user.is_active = False
            user.save()
            activationEmail(request, user, registerform.cleaned_data.get('email'))
            return HttpResponseRedirect('/login/')
        else:
            for error in registerform.errors.values():
                messages.error(request, error)
    
    context = {
        'registerform' : registerform,
        'mdomain' : mdomain,
    }
    
    return render(request, 'users/registration.html', context)

# Profile View

@login_required
def profileView(request):
    id = request.user.id
    user = get_user_model().objects.get(id=id)
    template = loader.get_template('users/profile.html')
    context = {
        'user' : user,
    }
    return HttpResponse(template.render(context, request))

# Profile Edit

@login_required
def profileEdit(request):
    id = request.user.id
    user = get_user_model().objects.get(id=id)
    profileform = CustomUserChangeForm(request.POST or None, instance = user)
    if profileform.is_valid():
        profileform.save()
        return HttpResponseRedirect('/users/profile/')
    else:
            for error in profileform.errors.values():
                messages.error(request, error)
    context = {
        'profileform': profileform,
    }
    return render(request, 'users/profile_edit.html', context)

# Password Change

@login_required
def passwordChange(request):
    user = request.user
    if request.method == 'POST':
        changepasswordform = ChangePasswordForm(request.POST, instance=user)
        if changepasswordform.is_valid():
            changepasswordform.save()
            return HttpResponseRedirect('/login/')
        else:
            for error in changepasswordform.errors.values():
                messages.error(request, error)
    else:
        changepasswordform = ChangePasswordForm(instance=user)
    context = {
        'changepasswordform': changepasswordform,
    }
    return render(request, 'users/password_change.html', context)

# Password Reset

@user_not_authenticated
def passwordResetRequest(request):
    if request.method == 'POST':
        passwordresetform = PasswordResetForm(request.POST)
        if passwordresetform.is_valid():
            user_email = passwordresetform.cleaned_data['email']
            associated_user = get_user_model().objects.filter(Q(email = user_email)).first()
            if associated_user:
                mail_subject = _('Password Reset Request')
                message = render_to_string('users/password_reset_email.html', {
                'user': associated_user.first_name,
                'domain': get_current_site(request).domain,
                'uid' : urlsafe_base64_encode(force_bytes(associated_user.pk)),
                'token' : account_activation_token.make_token(associated_user),
                'protocol' : 'https' if request.is_secure() else 'http'
                })
                email = EmailMessage(mail_subject, message, to=[associated_user])
                try:
                    email.send()
                    messages.success(request, _("Please go to your email inbox and click on the included link to reset your password. <b>Note:</b> Remember to check your spam folder."))
                    return redirect('/login/')
                except:
                    messages.error(request, _('There was a problem sending the email. Please contact the Administrator'))
            else:
                messages.error(request, _('The email address provided is not registered.'))

            return redirect('/login/')
        
    passwordresetform = PasswordResetForm()
    context = {
        'passwordresetform': passwordresetform,
    }
    return render(request, 'users/password_reset.html', context)


def passwordResetConfirm(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        print(user)
        if request.method == 'POST':
            changepasswordform = ChangePasswordForm(request.POST, instance=user)
            if changepasswordform.is_valid():
                changepasswordform.save()
                messages.success(request, _("Your password has been set. You may go ahead and <b>login</b> now."))
                return redirect('/login/')
            else:
                for error in list(changepasswordform.errors.values()):
                    messages.error(request, error)

        changepasswordform = ChangePasswordForm(instance=user)
        return render(request, 'users/password_change.html', {'changepasswordform': changepasswordform})
    else:
        messages.error(request, _("Link is expired"))

    messages.error(request, _('Something went wrong, redirecting back to Homepage'))
    return redirect("/login/")

# Inactive Users list (Admin)

@login_required
@allowed_users(allowed_roles=['admin', 'administrator'])
def inactive_users(request, a, b):
    active = False
    users_list = get_user_model().objects.order_by('last_name').filter(is_active=False).exclude(is_superuser=True) [a:b]
    length = get_user_model().objects.filter(is_active=False).count()
    pgx = paginator(a, length, b)
    template = loader.get_template('users/users_inactive.html')
    context = {
        'users_list': users_list,
        'active' : active,
        'pgx' : pgx,
    }
    return HttpResponse(template.render(context, request))

# User profile view (Admin)

@login_required
@allowed_users(allowed_roles=['admin', 'administrator'])
def user(request, id):
    muser = get_user_model().objects.get(id=id)
    if muser.is_superuser == False:
        template = loader.get_template('users/user.html')
        context = {
            'muser' : muser,
        }
        return HttpResponse(template.render(context, request))
    else:
        return redirect('/admin_home/0/10/')

# Create User (Admin)

@login_required
@allowed_users(allowed_roles=['admin', 'administrator'])
def create_user(request):
    activeEnabled = checkUserCreationLimit()
    if request.method == 'POST':
        usercreateform = CustomUserCreationForm(request.POST)
        if usercreateform.is_valid():
            if activeEnabled:
                user = usercreateform.save()

mateapp-crm/templates/users/activate_account.html
{% load i18n %}
{% autoescape off %}
{% trans "Dear" %} {{ user }},

{% trans "Please click on the link below to complete your registration at MateApp Directory:" %}

{{ protocol }}://{{ domain }}/users/activate/{{ uid }}/{{ token }}

{% endautoescape %}

mateapp-crm/templates/users/create_user.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}

{% block navbar %}
{% include 'includes/admin_navbar.html' %}
{% endblock navbar %}

{% block content %}

<form method="post" autocomplete="off">

    {% csrf_token %}

    <div class="row row-col-1 py-3 justify-content-center">
        <div class="col m-5 p-4 border col-lg-5 rounded bg-white">
            <div style="text-align: center;">
                <h2>{% trans "Create User" %}</h2>
                </div>
            <br>
            <p>
                <div class="form-floating">
                    {{usercreateform.email}}
                    <label for="email" class="form-label">{% trans "eMail:" %}</label>
                </div>
            </p>
            <p>
                <div class="form-floating">
                    {{usercreateform.first_name}}
                    <label for="first_name" class="form-label">{% trans "First Name:" %}</label>
                </div>
            </p>
            <p>
                <div class="form-floating">
                    {{usercreateform.last_name}}
                    <label for="last_name" class="form-label">{% trans "Last Name:" %}</label>
                </div>
            </p>
            <p>
                <div class="form-floating">
                    {{usercreateform.password1}}
                    <label for="id_new_password1" class="form-label">{% trans "Password:" %}</label>
                </div>
            </p>
            <p>
            <div class="px-3">
                <ul class="list-unstyled">
                    <li><small>{% trans "Your password can’t be too similar to your other personal information." %}</small></li>
                    <li><small>{% trans "Your password must contain at least 8 characters." %}</small></li>
                    <li><small>{% trans "Your password can’t be a commonly used password." %}</small></li>
                    <li><small>{% trans "Your password can’t be entirely numeric." %}</small></li>
                </ul>
            </div>
            </p>
            <p>
                <div class="form-floating">
                    {{usercreateform.password2}}
                    <label for="id_new_password2" class="form-label">{% trans "Re-type Password:" %}</label>
                </div>
            </p>
            <div>
                {% if activeenabled %}
                <div class="form-check">
                    {{usercreateform.is_active}}
                    <label for="is_active" class="form-check-label">{% trans "Is Active?" %}</label>
                </div>
                {% else %}
                <div class="px-3">
                    <small>{% trans "Active user limit exceded. User will remain inactive until another one is disabled." %}</small>
                </div>
                {% endif %}
            </div>
            <p>
                <div class="form-floating">
                    {{usercreateform.role}}
                    <label for="id_role" class="form-label">{% trans "Role:" %}</label>
                </div>
            </p>

            <p>
                <div class="col d-flex justify-content-center px-5 py-3 col-lg-15">
                    <p><button class="btn btn-outline-success px-4 mx-2" type="submit">{% trans "Save" %}</button></p>
                    <p><a href="/admin_home/0/10/" class="btn btn-outline-secondary px-4 mx-2" role="button">{% trans "Cancel" %}</a></p>
                </div>
            </p>
        </div>
    </div>


</form>

{% endblock %}

mateapp-crm/templates/users/edit_user.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}

{% block navbar %}
{% include 'includes/admin_navbar.html' %}
{% endblock navbar %}

{% block content %}

<form method="post">

    {% csrf_token %}

    <div class="row row-col-1 py-3 justify-content-center">
        <div class="col m-5 p-4 border col-lg-5 rounded bg-white">
            <div style="text-align: center;">
                <h2>{% trans "Editing User:" %}</h2>
                <h3>{{muser.email}}</h3>
                </div>
            <br>
            <p>
                <div class="form-floating">
                    {{usercreateform.first_name}}
                    <label for="first_name" class="form-label">{% trans "First Name:" %}</label>
                </div>
            </p>
            <p>
                <div class="form-floating">
                    {{usercreateform.last_name}}
                    <label for="last_name" class="form-label">{% trans "Last Name:" %}</label>
                </div>
            </p>
            {% if user != muser %}
                <div>
                    {% if activeenabled %}
                    <div class="form-check">
                        {{usercreateform.is_active}}
                        <label for="is_active" class="form-check-label">{% trans "Is Active?" %}</label>
                    </div>
                    {% else %}
                    <div class="px-3">
                        <small>{% trans "User limit exceded. You must disable other user to enable this one." %}</small>
                    </div>
                    {% endif %}
                </div>
                <p>
                    <div class="form-floating">
                        {{usercreateform.role}}
                        <label for="id_role" class="form-label">{% trans "Role:" %}</label>
                    </div>
                </p>
            {% endif %}

            <p>
                <div class="col d-flex justify-content-center px-5 py-3 col-lg-15">
                    <p><button class="btn btn-outline-success px-4 mx-2" type="submit">{% trans "Save" %}</button></p>
                    <p><a href="/admin_home/0/10/" class="btn btn-outline-secondary px-4 mx-2" role="button">{% trans "Cancel" %}</a></p>
                </div>
            </p>
        </div>
    </div>


</form>

{% endblock %}

mateapp-crm/templates/users/password_change.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block navbar %}
{% include 'includes/navbar.html' %}
{% endblock navbar %}

{% block content %}

<form method="post">

    {% csrf_token %}

    <div class="row row-col-1 py-3 justify-content-center">
        <div class="col m-5 p-4 border col-lg-5 rounded bg-white">
            <div style="text-align: center;">
                <h2>{% trans "Password Change" %}</h2>
                </div>
            <br>
            <p>
                <div class="form-floating">
                    {{changepasswordform.password1}}
                    <label for="id_new_password1" class="form-label">{% trans "Password:" %}</label>
                </div>
            </p>
            <p>
            <div class="px-3">
                <ul class="list-unstyled">
                    <li><small>{% trans "Your password can’t be too similar to your other personal information." %}</small></li>
                    <li><small>{% trans "Your password must contain at least 8 characters." %}</small></li>
                    <li><small>{% trans "Your password can’t be a commonly used password." %}</small></li>
                    <li><small>{% trans "Your password can’t be entirely numeric." %}</small></li>
                </ul>
            </div>
            </p>
            <p>
                <div class="form-floating">
                    {{changepasswordform.password2}}
                    <label for="id_new_password2" class="form-label">{% trans "Re-type Password:" %}</label>
                </div>
            </p>
            <p>
                <div class="col d-flex justify-content-center px-5 py-3 col-lg-15">
                    <p><button class="btn btn-outline-success px-4 mx-2" type="submit">{% trans "Change" %}</button></p>
                    <p><a href="/users/profile/" class="btn btn-outline-secondary px-4 mx-2" role="button">{% trans "Cancel" %}</a></p>
                </div>
            </p>
        </div>
    </div>


</form>

{% endblock %}

mateapp-crm/templates/users/password_reset.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block navbar %}
{% include 'includes/navbar.html' %}
{% endblock navbar %}

{% block content %}
<form method="post">

    {% csrf_token %}

    <div class="row row-col-1 py-3 justify-content-center">
        <div class="col bg-white m-5 p-4 border col-lg-5 rounded">
            <div style="text-align: center">
                <h2>{% trans "Password Reset" %}</h2>
                </div>
            <br>
            <div class="px-3">
                <p>{% trans "Forgot you password? Enter your email below, and we'll email instructions for setting a new one." %}</p>
            </div>
            </p>
            <div class="form-floating">
                    {{passwordresetform.email}}
                    <label for="id_email" class="form-label">{% trans "eMail:" %}</label>
            </div>
            <p>
                <div class="col d-flex justify-content-center px-5 py-3 col-lg-15">
                    <p><button class="btn btn-outline-success px-4 mx-2" type="submit">{% trans "Send" %}</button></p>
                    <p><a href="/users/profile/" class="btn btn-outline-secondary px-4 mx-2" role="button">{% trans "Cancel" %}</a></p>
                </div>
            </p>
        </div>
    </div>


</form>


{% endblock content %}

mateapp-crm/templates/users/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% trans "Hello" %} {{ user }},

{% trans "We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below." %}

{{ protocol }}://{{ domain }}/users/password_reset_confirm/{{ uid }}/{{ token }}

{% trans "This link can only be used once. If you need to reset your password again, please visit" %} {{ protocol }}://{{domain}} {% trans "and request another reset." %}

{% trans "If you did not make this request, you can simply ignore this email." %}


{% endautoescape %}

mateapp-crm/templates/users/profile.html
{% extends 'main/base.html' %}
{% load static %}

{% block navbar %}
{% include 'includes/navbar.html' %}
{% endblock navbar %}

{% load i18n %}
{% block content %}

<div class="row row-col-2 py-3 justify-content-center">
    <div class="col bg-white mx-1 px-5 py-3 mb-2 border col-lg-5 rounded">
        <div style="text-align: center">
            <h2>{% trans "User Profile" %}</h2>
            </div>
        <br>
        <h4>{{user.first_name}} {{user.last_name}}</h4>
        <br>
        <h6> <strong>{% trans "eMail:" %}</strong> {{user.email}}</h6>
        <br>
        <h6><strong>{% trans "User Type:" %}</strong> {{user.role}}</h6>
        <br>
        {% if user.is_active %} 
        <h6><strong>{% trans "User Status:" %}</strong> {% trans "Active" %}</h6>
        {% else %}
        <h6><strong>{% trans "User Status:" %}</strong> {% trans "Inactive" %}</h6> 
        {% endif %}
        <br>
        <div style="text-align: center">
            <p><a href="/users/profile_edit/" class="btn btn-outline-success px-4 mx-3" role="button">{% trans "Edit" %}</a></p>
        </div>
    </div>
</div>

{% endblock %}

mateapp-crm/templates/users/users_inactive.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block navbar %}
{% include 'includes/admin_navbar.html' %}
{% endblock navbar %}

{% block content %}

<!-- Header Users -->
<div class="row mt-3 justify-content-md-center">
    <div class="col bg-white p-2 col-lg-10 mx-1 rounded border">
      <div class="container-fluid px-4">
        <h4><i class="bi bi-person-slash"></i>&nbsp;{% trans "Inactive Users" %}</h4>
      </div>
    </div> 
</div>

<!-- Content -->
<div class="row mt-3 justify-content-md-center">
    <div class="col bg-white p-3 mx-1 border rounded col-lg-10">
    {% if users_list %}

      <!-- Table md -->
      <div class="table-responsive d-none d-sm-block">
        <table class="table table-hover" id="users_list" name="Users_List">

          <!-- Cabecera de Tabla -->
          <thead class="table-secondary">
              <th>{% trans "Name" %}</th>
              <th>{% trans "eMail" %}</th>
              <th>{% trans "Status" %}</th>
              <th>{% trans "Is Supervisor?" %}</th>
          </thead>

          <!-- Cuerpo de Tabla -->
          <tbody>
              {% for User in users_list %}
              <tr>
                  <td><a class="nav-link" href="/users/user/{{ User.id }}/">{{ User.last_name }}, {{ User.first_name }}</a></td>
                  <td>{{ User.email}}</td>
                  {% if User.is_active %}
                  <td class='text-success'>{% trans "Active" %}</td>
                  {% else %}
                  <td class='text-danger'>{% trans "Inactive" %}</td>
                  {% endif %}
                  {% if User.role == 'Administrator'%}
                  <td class='text-success'>{% trans "Yes" %}</td>
                  {% else %}
                  <td>{% trans "No" %}</td>
                  {% endif %}
              </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>

      <!-- Table sm -->
      <div class="table-responsive d-block d-sm-none">
        <table class="table table-hover" id="users_list" name="Users_List">

          <!-- Cabecera de Tabla -->
          <thead class="table-secondary">
              <th>{% trans "Name" %}</th>
              <th>{% trans "Status" %}</th>
          </thead>

          <!-- Cuerpo de Tabla -->
          <tbody>
              {% for User in users_list %}
              <tr>
                  <td><a class="nav-link" href="/users/user/{{ User.id }}/">{{ User.last_name }}, {{ User.first_name }}</a></td>
                  {% if User.is_active %}
                  <td class='text-success'>{% trans "Active" %}</td>
                  {% else %}
                  <td class='text-danger'>{% trans "Inactive" %}</td>
                  {% endif %}
              </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>

    <!-- Pagination -->
    {% if pgx.pgs > 1 %}
      <nav aria-label="Page navigation">
          <ul class="pagination">
            <li class="page-item">
              <a class="page-link" href="{% url 'users:inactiveUsers' a=pgx.idxpl b=pgx.idxpr %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            {% for link in pgx.lks %}
            <li class="page-item"><a class="page-link" id="page-link" href="{% url 'users:inactiveUsers' a=link.pl b=link.pr %}">{{link.page}}</a></li>
            {% endfor %}
            <li class="page-item">
              <a class="page-link" href="{% url 'users:inactiveUsers' a=pgx.idxnl b=pgx.idxnr %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav>
    {% endif %}

    {% else %}
        <p>{% trans "No users available." %}</p>
    {% endif %}

  </div>
</div>
{% endblock %}