mateapp-crm/directory/urls.py
from django.urls import path, include
from .api import CompanyViewSet, AddressViewSet, PersonViewSet, LeadViewSet
from . import views
from rest_framework import routers

app_name = 'directory'

router = routers.DefaultRouter()
router.register(r'companies', CompanyViewSet, 'companies')
router.register(r'address', AddressViewSet, 'address')
router.register(r'persons', PersonViewSet, 'persons')
router.register(r'leads', LeadViewSet, 'leads')

urlpatterns = [
    path('', views.index, name='Index'),
    # List
    path('persons/', views.persons, name='Persons'),
    path('companies/', views.companies, name='Companies'),
    path('person/<int:id>/', views.person, name='Person'),
    path('company/<int:id>/<int:a>/<int:b>/', views.company, name='Company'),
    # CUD Person
    path('create_person/', views.create_person, name='CreatePerson'),
    path('edit_person/<int:id>/', views.edit_person, name='EditPerson'),
    path('delete_person/<int:id>/', views.delete_person, name='DeletePerson'),
    path('restore_person/<int:id>/<int:u>/', views.restore_person, name='RestorePerson'),
    path('full_delete_person/<int:id>/', views.full_delete_person, name='FullDeletePerson'),
    path('person_notes/<int:id>/', views.personNotes, name='personNotes'),
    path('person_notes_title/<int:id>/', views.personNotesTitle, name='personNotesTitle'),
    path('edit_person_notes/<int:id>/', views.personNotesEdit, name='personNotesEdit'),
    path('create_person_post/<int:id>/', views.personPostCreate, name='personPostCreate'),
    path('person_sticky/<int:id>/<int:pid>/', views.person_sticky, name='personSticky'),
    #  CUD Company
    path('create_company/', views.create_company, name='CreateCompany'),
    path('edit_company/<int:id>/', views.edit_company, name='EditCompany'),
    path('delete_company/<int:id>/', views.delete_company, name='DeleteCompany'),
    path('restore_company/<int:id>/<int:u>/', views.restore_company, name='RestoreCompany'),
    path('full_delete_company/<int:id>/', views.full_delete_company, name='FullDeleteCompany'),
    path('company_notes/<int:id>/', views.companyNotes, name='companyNotes'),
    path('company_notes_title/<int:id>/', views.companyNotesTitle, name='companyNotesTitle'),
    path('edit_company_notes/<int:id>/', views.companyNotesEdit, name='companyNotesEdit'),
    path('company_persons_list/<int:id>/<int:a>/<int:b>/', views.companyPersons, name='companyPersons'),
    path('company_persons_collapsed/<int:id>/', views.companyPersonsCollapsed, name=('companyPersonsCollapsed')),
    path('create_company_post/<int:id>/', views.companyPostCreate, name='companyPostCreate'),
    path('company_sticky/<int:id>/<int:cid>/', views.company_sticky, name='companySticky'),
    # Favorites
    path('link_fav/<str:obj>/<int:oid>/', views.link_favorite, name='LinkFav'),
    path('unlink_fav/<int:lid>/', views.unlink_favorite, name='UnLinkFav'),
    path('favs/', views.favs, name='Favs'),
    path('unlink_fav_favs/<int:lid>/', views.unlink_favorite_favs, name='UnLinkFavFavs'),
    #  API
    path('api/', include(router.urls))
]

mateapp-crm/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('search/', views.search, name='search'),
    path('login/', views.login, name='login'),
    path('signout/', views.signout, name='Logout'),
    path('user_trash/<int:a>/<int:b>/', views.user_trash, name='User_Trash'),
    path('admin_trash/<int:a>/<int:b>/', views.admin_trash, name='Admin_Trash'),
    path('admin_home/<int:a>/<int:b>/', views.admin_home, name='Admin_Home'),
    path('backup/', views.do_backup, name='Backup'),
]

mateapp-crm/posts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.post_create, name='create'),
    path('list/', views.posts_list, name='list'),
    #path('posts_list/', views.posts_list, name='posts_list'),
    path('view/<int:id>/', views.post_view, name='view'),
    path('post_title/<int:id>/', views.post_title, name='title'),
    path('post_post/<int:id>/', views.post_post, name='post'),
    path('post_edit/<int:id>/', views.post_edit, name='edit'),
    # path('post_action/<int:id>/', views.post_action, name='action'),
    path('post_delete/<int:id>/', views.post_delete, name='delete'),
    path('post_restore/<int:id>/', views.post_restore, name='restore'),
    path('post_full_delete/<int:id>/', views.post_full_delete, name='full_delete'),
    path('upload/<int:id>/', views.file_upload, name='upload'),
    path('files/<int:id>/', views.files, name='files'),
    path('fileslist/<int:id>', views.files_list, name='fileslist'),
    path('filedelete/<int:fid>/<int:pid>', views.file_delete, name='filedelete'),
    # path('edit/', views.***, name='edit'),
]

mateapp-crm/directory/models.py
from django.db import models
from django.conf import settings
from datetime import date

class BaseModel(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(blank=True, default=0)
    deletedBy = models.BigIntegerField(blank=True, null=True)
    
    class Meta:
        abstract = True

class Address(BaseModel):
    street = models.CharField(max_length=200, blank=True)
    postalCode = models.CharField(max_length=7, blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f'{self.street}, {self.city}'

class Company(BaseModel):
    companyName = models.CharField(max_length=100, blank=True)
    tax_id = models.CharField(max_length=15, blank=True)
    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING, blank=True, null=True)
    website = models.CharField(max_length=100, blank=True)
    companyPhone = models.CharField(max_length=25, blank=True)
    companyNotes = models.TextField(max_length=2000, blank=True)
    companyNotes_title = models.CharField(max_length=200, blank=True, null=True)

    def title(self):
        fline = self.companyNotes.split('\n', 1)[0]
        if len(fline) > 25:
            fline = fline[:25]
            title = f'{fline}...'
        else:
            title = fline
        return title

    def save(self, *args, **kwargs):
        self.companyNotes_title = self.title()
        super(Company, self).save(*args, **kwargs)

    def __str__(self):
        return self.companyName


class Person(BaseModel):
    lastName = models.CharField(max_length=50, blank=True)
    firstName = models.CharField(max_length=50, blank=True)
    celphone = models.CharField(max_length=25, blank=True)
    workphone = models.CharField(max_length=25, blank=True)
    email = models.CharField(max_length=100, blank=True)
    position = models.CharField(max_length=50, blank=True)
    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING, blank=True, null=True)
    notes = models.TextField(max_length=2000, blank=True)
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING, blank=True, null=True)
    notes_title = models.CharField(max_length=200, blank=True, null=True)

    def title(self):
        fline = self.notes.split('\n', 1)[0]
        if len(fline) > 25:
            fline = fline[:25]
            title = f'{fline}...'
        else:
            title = fline
        return title

    def save(self, *args, **kwargs):
        self.notes_title = self.title()
        super(Person, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.lastName}, {self.firstName}'


class Favorite(BaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, blank=True, null=True)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING, blank=True, null=True)
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING, blank=True, null=True)

class Lead(BaseModel):
    firstName = models.CharField(max_length=100, blank=True)
    lastName = models.CharField(max_length=100, blank=True)
    email = models.EmailField(unique=False)
    message = models.CharField(max_length=500, blank=True)
    messageDate = models.DateField(blank=True, null=True, default=date.today)

    def __str__(self):
        return f'{self.lastName} - {self.messageDate}'

mateapp-crm/directory/forms.py
from django import forms
from .models import Person, Company, Address
from django.utils.translation import gettext_lazy as _

class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = [
            'firstName',
            'lastName',
            'position',
            'celphone',
            'workphone',
            'email',
            'company',
            'notes',
        ]

        widgets = {
            'firstName': forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}),
            'lastName': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}),
            'position': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Position'}),
            'celphone': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Cell Phone'}),
            'workphone': forms.TextInput(attrs={'class':'form-control','placeholder':'Work Phone'}),
            'email': forms.TextInput(attrs={'class':'form-control','placeholder':'eMail','type':'email'}),
            'company': forms.Select(attrs={'class':'form-select'}),
            'notes': forms.Textarea(attrs={'class':'form-control','placeholder':'Notes','style':'height: 200px'}),
        }

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        self.fields['company'].queryset = Company.objects.filter(deleted=False).order_by('companyName')
        self.fields['company'].empty_label = _("Select Company:")

class CompanyForm(forms.ModelForm):

    class Meta:
        model = Company
        fields = [
            'companyName',
            'tax_id',
            'website',
            'companyPhone',
            'address',
            'companyNotes',
        ]

        widgets = {
            'companyName': forms.TextInput(attrs={'class':'form-control','placeholder':'Company Name'}),
            'tax_id': forms.TextInput(attrs={'class':'form-control','placeholder':'Tax ID'}),
            'website': forms.TextInput(attrs={'class':'form-control','placeholder':'Website'}),
            'companyPhone': forms.TextInput(attrs={'class':'form-control','placeholder':'Company Phone'}),
            'companyNotes': forms.Textarea(attrs={'class':'form-control','placeholder':'Company Notes','style':'height: 200px'}),
        }

class AddressFrom(forms.ModelForm):

    class Meta:
        model = Address
        fields = [
            'street',
            'postalCode',
            'city',
            'state',
            'country',
        ]

        widgets = {
            'street': forms.TextInput(attrs={'class':'form-control','placeholder':'Street'}),
            'postalCode': forms.TextInput(attrs={'class':'form-control','placeholder':'Postal Code'}),
            'city': forms.TextInput(attrs={'class':'form-control','placeholder':'City'}),
            'state': forms.TextInput(attrs={'class':'form-control','placeholder':'State'}),
            'country': forms.TextInput(attrs={'class':'form-control','placeholder':'Country'}),
        }

class PersonNotesForm(forms.ModelForm):
    '''Short form for partial edit with htmx'''

    class Meta:
        model = Person
        fields = {
            'notes',
        }

        widgets = {
            'notes': forms.Textarea(attrs={'class':'form-control','placeholder':'Notes','style':'height: 200px'}),
        }

class CompanyNotesForm(forms.ModelForm):
    '''Short form for partial edit with htmx'''

    class Meta:
        model = Company
        fields = {
            'companyNotes',
        }

        widgets = {
            'companyNotes': forms.Textarea(attrs={'class':'form-control','placeholder':'Notes','style':'height: 200px'}),
        }

mateapp-crm/templates/directory/partials/company_notes.html
{% load i18n %}
<div class="row py-3 justify-content-start" id="notes" hx-swap="outerHTML swap:0.2s" hx-target="#notes">
    <div class="col p-3 col-lg-10 hx-pointer" hx-get="{% url 'directory:companyNotesTitle' id=company.id %}">
        {{company.companyNotes|linebreaks}}<span><small>{% trans "< less" %}&nbsp;|&nbsp;</small></span>
    </div>
</div>

mateapp-crm/templates/directory/partials/company_notes_title.html
{% load i18n %}

<div class="row justify-content-start" id="notes" hx-swap="outerHTML swap:0.2s" hx-target="#notes">
    <div class="col py-1 col-lg-10">
        <span><i class="bi bi-pencil-square text-success h5 hx-pointer me-2" hx-get="{% url 'directory:companyNotesEdit' id=company.id %}"></i></span>{{ company.companyNotes_title }} 
        <span class="hx-pointer" hx-get="{% url 'directory:companyNotes' id=company.id %}"><small>&nbsp;|&nbsp;{% trans "more >" %}</small></span>
    </div>
</div>

mateapp-crm/templates/directory/partials/company_persons_collapsed.html
{% load i18n %}

<div class="row justify-content-start" id="persons_list" hx-swap="outerHTML swap:0.2s" hx-target="#persons_list">
    <div class="col py-1 col-lg-10">
        <span class="btn btn-outline-secondary btn-sm" hx-get="{% url 'directory:companyPersons' id=company.id a=0 b=5 %}">{% trans "Persons" %}&nbsp;<i class="bi bi-arrow-right"></i></span>
    </div>
</div>

mateapp-crm/templates/directory/partials/company_persons_list.html
{% load i18n %}

<div id="persons_list">
    <div class="col py-1 col-lg-10">
        <span class="btn btn-outline-secondary btn-sm mb-2" hx-get="{% url 'directory:companyPersonsCollapsed' id=company.id %}" hx-swap="outerHTML swap:0.2s" hx-target="#persons_list"><i class="bi bi-arrow-left"></i>&nbsp;{% trans "Persons" %}</span>
    </div>
    <!-- Table md -->
    <div class="table-responsive d-none d-sm-block">
        <table class="table table-hover" id="person_list" name="Person_List">
            <!-- Cabecera de Tabla -->
            <thead class="table">
                <th>{% trans "Name" %}</th>
                <th>{% trans "eMail" %}</th>
                <th>{% trans "CellPhone" %}
                </th>
            </thead>

            <!-- Cuerpo de Tabla -->

            <tbody>
                {% for Person in person_list %}
                <tr>
                    <td><a class="nav-link" href="/directory/person/{{ Person.id }}/">{{ Person.lastName }}, {{ Person.firstName }}</a></td>
                    <td><a class="nav-link" href="mailto:{{Person.email}}">{{Person.email}}</a></td>
                    <td>{{ Person.celphone }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Table xs -->
    <div class="table-responsive d-block d-sm-none">
        <table class="table table-hover" id="person_list" name="Person_List">
            <!-- Cabecera de Tabla -->
            <thead class="table">
                <th>{% trans "Name" %}</th>
                <th>{% trans "CellPhone" %}
                </th>
            </thead>

            <!-- Cuerpo de Tabla -->

            <tbody>
                {% for Person in person_list %}
                <tr>
                    <td><a class="nav-link" href="/directory/person/{{ Person.id }}/">{{ Person.lastName }}, {{ Person.firstName }}</a></td>
                    <td>{{ Person.celphone }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% if pgx.pgs > 1 %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
          <li class="page-item">
            <span class="page-link hx-pointer" hx-get="{% url 'directory:companyPersons' id=company.id a=pgx.idxpl b=pgx.idxpr %}" hx-target="#persons_list" hx-swap="outerHTML"  aria-label="Previous">
              <span>&laquo;</span>
            </span>
          </li>
          {% for link in pgx.lks %}
            {% if pgx.pn == link.page %}
                <li class="page-item"><span class="page-link hx-pointer active" id="page-link" hx-get="{% url 'directory:companyPersons' id=company.id a=link.pl b=link.pr %}" hx-target="#persons_list" hx-swap="outerHTML">{{link.page}}</span></li>
            {% else %}
                <li class="page-item"><span class="page-link hx-pointer" id="page-link" hx-get="{% url 'directory:companyPersons' id=company.id a=link.pl b=link.pr %}" hx-target="#persons_list" hx-swap="outerHTML">{{link.page}}</span></li>
            {% endif %}
          {% endfor %}
          <li class="page-item">
            <span class="page-link hx-pointer" hx-get="{% url 'directory:companyPersons' id=company.id a=pgx.idxnl b=pgx.idxnr %}" hx-target="#persons_list" hx-swap="outerHTML"  aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </span>
          </li>
        </ul>
    </nav>
    {% endif %}
</div>

mateapp-crm/templates/directory/partials/company_post_create.html
{% load static %}
{% load i18n %}

<div class="row mt-3 justify-content-md-center">
    <div class="col col-lg-10 rounded border bg-white p-4 mx-1">
        <form hx-put="{% url 'directory:companyPostCreate' id=company.id %}" hx-target="#list" hx-swap="outerHTML swap:0.2s">
            {% csrf_token %}
            <div class='mb-2'>
                {{ postcreationform.post }}
            </div>
            <div class="my-3">
                {{ postcreationform.person }}
            </div>
            <button type="submit" class="btn btn-outline-success btn-sm me-2">{% trans "Save" %}</button>
            <button class="btn btn-outline-secondary btn-sm" hx-get="{% url 'directory:Company' id=company.id a=0 b=5%}" hx-target="#list">{% trans "Cancel" %}</button>

        </form>
    </div>  
</div>

mateapp-crm/templates/directory/partials/company_posts_list.html
{% load i18n %}
<!--target div for the list partial -->
<div id="list">
    <!--target div for the create partial -->
    <div id="create"></div>

    {% if page_obj %}
    {% for post in page_obj  %}

    <!--This div contains the card list page for infinite scrolling -->
    {% if forloop.last %}
        {% if  page_obj.number < page_obj.paginator.num_pages %}
            <div hx-get="{% url 'directory:Company' id=company.id a=0 b=5 %}?page={{ page_obj.number|add:1 }}" hx-trigger="revealed" hx-swap="afterend" hx-target="this">
        {% endif %}
    {% else %}
    <div>
    {% endif %}

        <!--Card-->
        <div class="row mt-2 justify-content-md-center" id="card" hx-target="this" hx-swap="outerHTML swap:0.5s">
            <div class="col col-lg-10 p-3 mx-1 rounded border bg-white">
                <div class="row row row-col-2 px-3 justify-content-start">
                    <div class="col col-10 col-lg-8 px-3 pt-1">
                        <strong><a class="nav-link" href="/directory/person/{{ post.person.id }}/">{{ post.person.firstName }}
                        {{ post.person.lastName }}</a></strong>
                        <div class="my-3">
                            {% include 'posts/partials/post_title.html' %}
                        </div>     
                    </div>
                    <div class="col col-10 col-lg-4 pt-1 light-border-lg">
                        <div>
                            <small>{% trans "Created on " %}{{ post.date }}{% trans " by " %}{{ post.user.first_name }} {{ post.user.last_name }}.</small>
                        </div>
                        <div class="ms-3 my-2"> 
                            {% if post.action %}
                            <span hx-get="{% url 'directory:companySticky' id=post.id cid=company.id %}" hx-target="#list"><i class="bi bi-sticky-fill h5 hx-pointer text-warning me-4"></i></span>
                            {% else %}
                            <span hx-get="{% url 'directory:companySticky' id=post.id cid=company.id %}" hx-target="#list"><i class="bi bi-sticky h5 hx-pointer text-warning me-4"></i></span>
                            {% endif %}
                            <span class="me-4" hx-delete="{% url 'posts:delete' id=post.id %}"><i class="bi bi-trash h5 hx-pointer text-secondary"></i></span>
                            <span id="upload_{{post.id}}">{% include 'posts/partials/files.html' %}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>

mateapp-crm/templates/directory/partials/edit_company_notes.html
{% load i18n %} 

<form hx-put="{% url 'directory:companyNotesEdit' id=company.id %}" hx-target="#notes" hx-swap="outerHTML swap:0.2s" id="notes">

    {% csrf_token %}

    <div class="form-floating my-2">
        {{notesform.companyNotes}}
        <label for="id_notes">{% trans "Notes:" %}</label>
    </div>
    <button class="btn btn-outline-success btn-sm">{% trans "Save" %}</button>
    <button class="btn btn-outline-secondary btn-sm" hx-get="{% url 'directory:companyNotesTitle' id=company.id %}" hx-target="#notes">{% trans "Cancel" %}</button>

</form>

mateapp-crm/templates/directory/partials/edit_person_notes.html
{% load i18n %} 

<form hx-put="/directory/edit_person_notes/{{ person.id }}/" hx-target="#notes" hx-swap="outerHTML swap:0.2s" id="notes">

    {% csrf_token %}

    <div class="form-floating my-2">
        {{notesform.notes}}
        <label for="id_notes">{% trans "Notes:" %}</label>
    </div>
    <button class="btn btn-outline-success btn-sm">{% trans "Save" %}</button>
    <button class="btn btn-outline-secondary btn-sm" hx-get="{% url 'directory:personNotesTitle' id=person.id %}" hx-target="#notes">{% trans "Cancel" %}</button>

</form>

mateapp-crm/templates/directory/partials/person_notes.html
{% load i18n %}

<div class="row py-3 justify-content-start" id="notes" hx-swap="outerHTML swap:0.2s" hx-target="#notes">
    <div class="col p-3 col-lg-10 hx-pointer" hx-get="{% url 'directory:personNotesTitle' id=person.id %}">
        {{person.notes|linebreaks}}<span><small>{% trans "< less" %}&nbsp;|&nbsp;</small></span>
    </div>
</div>

mateapp-crm/templates/directory/partials/person_notes_title.html
{% load i18n %}

<div class="row justify-content-start" id="notes" hx-swap="outerHTML swap:0.2s" hx-target="#notes">
    <div class="col py-1 col-lg-10">
        <span><i class="bi bi-pencil-square text-success h5 hx-pointer me-2" hx-get="{% url 'directory:personNotesEdit' id=person.id %}"></i></span>{{ person.notes_title }} 
        <span class="hx-pointer" hx-get="{% url 'directory:personNotes' id=person.id %}"><small>&nbsp;|&nbsp;{% trans "more >" %}</small></span>
    </div>
</div>

mateapp-crm/templates/directory/partials/person_post_create.html
{% load static %}
{% load i18n %}

<div class="row mt-3 justify-content-md-center">
    <div class="col col-lg-10 rounded border bg-white p-4 mx-1">
        <form hx-put="{% url 'directory:personPostCreate' id=person.id %}" hx-target="#list" hx-swap="outerHTML swap:0.2s">
            {% csrf_token %}
            <div class='mb-2'>
                {{ postcreationform.post }}
            </div>
            <button type="submit" class="btn btn-outline-success btn-sm me-2">{% trans "Save" %}</button>
            <button class="btn btn-outline-secondary btn-sm" hx-get="{% url 'directory:Person' id=person.id %}" hx-target="#list">{% trans "Cancel" %}</button>

        </form>
    </div>  
</div>

mateapp-crm/templates/directory/partials/person_posts_list.html
{% load i18n %}
<!--target div for the list partial -->
<div id="list">
    <!--target div for the create partial -->
    <div id="create"></div>

    {% if page_obj %}
    {% for post in page_obj  %}

    <!--This div contains the card list page for infinite scrolling -->
    {% if forloop.last %}
        {% if  page_obj.number < page_obj.paginator.num_pages %}
            <div hx-get="{% url 'directory:Person' id=person.id %}?page={{ page_obj.number|add:1 }}" hx-trigger="revealed" hx-swap="afterend" hx-target="this">
        {% endif %}
    {% else %}
    <div>
    {% endif %}

        <!--Card-->
        <div class="row mt-2 justify-content-md-center" id="card_{{post.id}}" hx-target="this" hx-swap="outerHTML swap:0.5s">
            <div class="col col-lg-10 p-3 mx-1 rounded border bg-white">
                <div class="row row row-col-2 px-3 justify-content-start">
                    <div class="col col-10 col-lg-8 px-3 pt-1 my-3">
                        <div>
                            {% include 'posts/partials/post_title.html' %}
                        </div>     
                    </div>
                    <div class="col col-10 col-lg-4 pt-1 light-border-lg">
                        <div>
                            <small>{% trans "Created on " %}{{ post.date }}{% trans " by " %}{{ post.user.first_name }} {{ post.user.last_name }}.</small>
                        </div>
                        <div class="ms-3 my-2"> 
                            {% if post.action %}
                            <span hx-get="{% url 'directory:personSticky' id=post.id pid=person.id %}" hx-target="#list"><i class="bi bi-sticky-fill h5 hx-pointer text-warning me-4"></i></span>
                            {% else %}
                            <span hx-get="{% url 'directory:personSticky' id=post.id pid=person.id %}" hx-target="#list"><i class="bi bi-sticky h5 hx-pointer text-warning me-4"></i></span>
                            {% endif %}
                            <span class="me-4" hx-delete="{% url 'posts:delete' id=post.id %}"><i class="bi bi-trash h5 hx-pointer text-secondary"></i></span>
                            <span id="upload_{{post.id}}">{% include 'posts/partials/files.html' %}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>