mateapp-crm/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('search/', views.search, name='search'),
    path('login/', views.login, name='login'),
    path('signout/', views.signout, name='Logout'),
    path('user_trash/<int:a>/<int:b>/', views.user_trash, name='User_Trash'),
    path('admin_trash/<int:a>/<int:b>/', views.admin_trash, name='Admin_Trash'),
    path('admin_home/<int:a>/<int:b>/', views.admin_home, name='Admin_Home'),
    path('backup/', views.do_backup, name='Backup'),
]

mateapp-crm/posts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.post_create, name='create'),
    path('list/', views.posts_list, name='list'),
    #path('posts_list/', views.posts_list, name='posts_list'),
    path('view/<int:id>/', views.post_view, name='view'),
    path('post_title/<int:id>/', views.post_title, name='title'),
    path('post_post/<int:id>/', views.post_post, name='post'),
    path('post_edit/<int:id>/', views.post_edit, name='edit'),
    # path('post_action/<int:id>/', views.post_action, name='action'),
    path('post_delete/<int:id>/', views.post_delete, name='delete'),
    path('post_restore/<int:id>/', views.post_restore, name='restore'),
    path('post_full_delete/<int:id>/', views.post_full_delete, name='full_delete'),
    path('upload/<int:id>/', views.file_upload, name='upload'),
    path('files/<int:id>/', views.files, name='files'),
    path('fileslist/<int:id>', views.files_list, name='fileslist'),
    path('filedelete/<int:fid>/<int:pid>', views.file_delete, name='filedelete'),
    # path('edit/', views.***, name='edit'),
]

mateapp-crm/posts/models.py
from django.db import models
from django.conf import settings

from directory.models import Person, Company

class BaseModel(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(blank=True, default=0)
    deletedBy = models.BigIntegerField(blank=True, null=True)
    
    class Meta:
        abstract = True

class Post(BaseModel):
    post = models.TextField(max_length=2000, blank=True, null=True)
    action = models.BooleanField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, blank=True, null=True)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING, blank=True, null=True)
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING, blank=True, null=True)
    post_title = models.CharField(max_length=200, blank=True, null=True)
    
    def title(self):
        fline = self.post.split('\n', 1)[0]
        if len(fline) > 25:
            fline = fline[:25]
            title = f'{fline}...'
        else:
            title = fline
        return title

    def save(self, *args, **kwargs):
        self.post_title = self.title()
        super(Post, self).save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.person} {self.company}: {self.post_title}'

class File(BaseModel):
    name = models.CharField(max_length=200, null=True)
    file = models.FileField(upload_to='posts', null=True)
    post = models.ForeignKey(Post, on_delete=models.DO_NOTHING, blank=True, null=True)
    shortName = models.CharField(max_length=30, null=True)
    color = models.CharField(max_length=20, null=True)
    ext = models.CharField(max_length=20, null=True)

mateapp-crm/posts/forms.py
from django import forms
from .models import Post, File
from directory.models import Person, Company
from django.utils.translation import gettext_lazy as _

class PostCreationForm(forms.ModelForm):  
    class Meta:
        model = Post 
        fields = [
            'post',
            'person',
            'company',
        ]

        widgets = {
            'post': forms.Textarea(attrs={'class':'form-control','placeholder':'Notes','style':'height: 200px'}),
            'person' : forms.Select(attrs={'class':'form-select'}),
            'company' : forms.Select(attrs={'class':'form-select'}),
        }

    def __init__(self, *args, **kwargs):
        super(PostCreationForm, self).__init__(*args, **kwargs)
        self.fields['company'].queryset = Company.objects.filter(deleted=False).order_by('companyName')
        self.fields['company'].empty_label = _("Select Company:")
        self.fields['person'].queryset = Person.objects.filter(deleted=False).order_by('lastName')
        self.fields['person'].empty_label = _("Select Person:")

class PostEditForm(forms.ModelForm):
     '''Short form for partial edit with htmx'''

     class Meta:
        model = Post
        fields = {
            'post',
        }

        widgets = {
            'post': forms.Textarea(attrs={'class':'form-control','placeholder':'Notes','style':'height: 200px'}),
        }


class UploadFileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = [
            'file',
        ]

        widgets = {
            'file': forms.ClearableFileInput(attrs={'class':'form-control', 'type':'file', 'multiple' : ''})
        }

mateapp-crm/posts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, QueryDict, HttpResponse
from django.template import loader
from .forms import PostCreationForm, UploadFileForm, PostEditForm
from django.contrib.auth import get_user_model
from .models import Post, File
from django.db.models.functions import TruncDate
from django.db.models import Value, Count
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .functions import splitFilename
from django.conf import settings


##############
# Post Views #
##############

# Post Create

@login_required
def post_create(request):
    uid = request.user.id
    user = get_user_model().objects.get(id=uid)
    if request.method == 'PUT':
        data = QueryDict(request.body).dict()
        postcreationform = PostCreationForm(data)
        if postcreationform.is_valid():
            post = postcreationform.save(commit=False)
            post.user = user
            post.save()
            id = post.id
            return HttpResponseRedirect(reverse_lazy("posts:list"))
    else:
        postcreationform = PostCreationForm()

    context = {
        'postcreationform' : postcreationform,
    }
    return render(request, 'posts/partials/post_create.html', context)

# Post View DEPRECATED

@login_required
def post_view(request, id):
    post = Post.objects.get(id=id)

    context = {
        'post' : post,
    }
    return render(request, 'posts/view_post.html', context)

# Post List

@login_required
def posts_list(request):
    posts_list = Post.objects.order_by('-modified_date').filter(deleted=False).annotate(date=TruncDate('create_date'))
    paginator = Paginator(posts_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj' : page_obj
    }
    if request.htmx:
        return render(request, 'posts/partials/posts_list.html', context)
    else:
        return render(request, 'posts/list_posts.html', context)

# Post htmx partial view

@login_required
def post_post(request, id):
    '''Esta vista de la de display del partial del contenido del post en htmx'''
    post = Post.objects.get(id=id)
    files = File.objects.filter(post=post, deleted=False)
    path = f'{settings.MEDIA_URL}'
    context = {
        'post' : post,
        'files' : files,
        'path' : path,
    }
    return render(request, 'posts/partials/post_post.html', context)

# Post htmx collapsed view

@login_required
def post_title(request, id):
    '''Esta vista de la de display del partial del contenido del título del post en htmx'''
    post = Post.objects.get(id=id)
    context = {
        'post' : post,
    }
    return render(request, 'posts/partials/post_title.html', context)

# Post Edit

@login_required
def post_edit(request, id):
    '''Edición de post en htmx'''
    post = Post.objects.get(id=id)
    files = File.objects.filter(post=post, deleted=False)
    path = f'{settings.MEDIA_URL}'
    if request.method == 'PUT':
        data = QueryDict(request.body).dict()
        postform = PostEditForm(data, instance=post)
        if postform.is_valid():
            postform.save()
            context = {
            'postform' : postform,
            'post' : post,
            }
            return render(request, 'posts/partials/post_title.html', context)

    else:
        postform = PostEditForm(instance=post)

    context = {
        'postform' : postform,
        'post' : post,
        'files' : files,
        'path' : path,
    }
    return render(request, 'posts/partials/post_edit.html', context)

# Post htmx action switch

# @login_required
# def post_action(request, id):
#     post = Post.objects.get(id=id)
#     if post.action:
#         post.action = False
#         post.save()
#         return HttpResponse(f'<span hx-get="/posts/post_action/{id}/" hx-swap="outerHTML" hx-target="this"><i class="bi bi-star h5 hx-pointer text-primary me-4"></i></span>')
#     else:
#         post.action = True
#         post.save()
#         return HttpResponse(f'<span hx-get="/posts/post_action/{id}/" hx-swap="outerHTML" hx-target="this"><i class="bi bi-star-fill h5 hx-pointer text-primary me-4"></i></span>')

# Post Delete

@login_required
def post_delete(request, id):
    post = Post.objects.get(id=id)
    uid = request.user.id
    post.deleted = True
    post.deletedBy = uid
    post.save()
    return HttpResponse(status = 200)

# Post Restore

@login_required
def post_restore(request, id):
    post = Post.objects.get(id=id)
    post.deleted = False
    post.save()
    return HttpResponse(status = 200)

# Post Full Delete

@login_required
def post_full_delete(request, id):
    post = Post.objects.get(id=id)
    post.deletedBy = None
    post.save()
    return HttpResponse(status = 200)

##############
# File Views #
##############

def file_upload(request, id):
    post = Post.objects.get(id=id)
    upload_max_size = int(settings.UPLOAD_MAX_SIZE) * 1048576
    if request.method == 'POST':
        uploadfileform = UploadFileForm(request.POST, request.FILES)
        uploads = request.FILES.getlist('file')
        for upload in uploads:
            file = File.objects.create(file=upload)
            file.post = post
            name=str(upload)
            shortName, color, ext = splitFilename(name)
            file.shortName = shortName
            file.color = color
            file.ext = ext
            file.name = name
            file.save()
        return HttpResponseRedirect(f'/posts/files/{id}/')
    else:
        uploadfileform = UploadFileForm()

    context = {
        'uploadfileform': uploadfileform,
        'post' : post,
        'upload_max_size' : upload_max_size,
    }
    return render(request, 'posts/partials/upload.html', context)


def files(request, id):
    post = Post.objects.get(id=id)
    context = {
        'post' : post
    }
    return render(request, 'posts/partials/files.html', context)

def files_list(request, id):
    post = Post.objects.get(id=id)
    files = File.objects.filter(post=post, deleted=False)
    path = f'{settings.MEDIA_URL}'
    context = {
        'post' : post,
        'files' : files,
        'path' : path,
    }
    return render(request, 'posts/partials/files_list.html', context)

def file_delete(request, fid, pid):
    File.objects.filter(id=fid).delete()
    return HttpResponseRedirect(f'/posts/post_edit/{pid}')

mateapp-crm/templates/posts/partials/files.html
{% load i18n %}
<span hx-get="{% url 'posts:upload' id=post.id %}" hx-target="#upload_{{post.id}}"  hx-swap="outerHTML swap:0.2s" id="upload_{{post.id}}"><i class="bi bi-file-earmark-arrow-up h5 hx-pointer text-success me-4"></i>
</span>

mateapp-crm/templates/posts/partials/files_list.html
{% load i18n %}
<div class="my-2" hx-target="#files_{{post.id}}"  hx-swap="outerHTML swap:0.2s" id="files_{{post.id}}">
{% for file in files %}
<a class="badge text-bg-{{file.color}} nav-link" href="{{path}}{{file.file}}">{{file.shortName}}</a>
{% endfor %}
</div>

mateapp-crm/templates/posts/partials/post_create.html
{% load static %}
{% load i18n %}

<div class="row mt-3 justify-content-md-center">
    <div class="col col-lg-10 p-4 mx-1 border rounded bg-white">
        <form hx-put="{% url 'posts:create' %}" hx-target="#list" hx-swap="outerHTML swap:0.2s">
            {% csrf_token %}
            <div>
                {{ postcreationform.post }}
            </div>

            <div class="form-check form-switch my-3">
                <input class="form-check-input" type="checkbox" role="switch" id="slider", onclick="selectChoice()">
                <label class="form-check-label" for="slider">{% trans "Select by Company" %}</label>
            </div>
            <div class="my-3">
                {{ postcreationform.person }}
                {{ postcreationform.company }}
            </div>

            <button type="submit" class="btn btn-outline-success btn-sm me-2">{% trans "Save" %}</button>
            <button class="btn btn-outline-secondary btn-sm" hx-get="{% url 'posts:list' %}" hx-target="#list">{% trans "Cancel" %}</button>

        </form>
    </div>  
</div>

<script>
    var slider = document.getElementById("slider");
    var person = document.getElementById("id_person");
    var company = document.getElementById("id_company");

    person.style.display = "block";
    company.style.display = "none";

    function selectChoice(){

        if (slider.checked == true){
            person.style.display = "none";
            company.style.display = "block";
            company.required = true;
        } else {
            person.style.display = "block";
            person.required = true;
            company.style.display = "none";
        }

    }
</script>

mateapp-crm/templates/posts/partials/post_edit.html
{% load i18n %} 

<form class="mb-2" hx-put="{% url 'posts:edit' id=post.id %}" hx-target="this" hx-swap="outerHTML swap:0.2s" id="post">

    {% csrf_token %}

    <div class="form-floating my-2">
        {{postform.post}}
    </div>
    <div class="my-3">
        <i class="bi bi-paperclip h5 text-secondary me-2">></i>
        {% for file in files %}
        <span class="badge text-bg-{{file.color}}" hx-get="{% url 'posts:filedelete' fid=file.id pid=post.id %}" hx-confirm="{% trans "Are you sure? This action can't be undone!" %}">{{file.shortName}}&nbsp;&nbsp;<i class="bi bi-x-circle hx-pointer"></i></span>
        {% endfor %}
    </div>
    <button class="btn btn-outline-success btn-sm">{% trans "Save" %}</button>
    <button class="btn btn-outline-secondary btn-sm" hx-get="{% url 'posts:title' id=post.id %}">{% trans "Cancel" %}</button>

</form>

mateapp-crm/templates/posts/partials/post_post.html
{% load i18n %}
<div id="post" hx-swap="outerHTML swap:0.2s" hx-target="this">
    <div class="row px-3 mb-2 justify-content-start">
        <div class="col mt-3 py-1 px-3 col-lg-10 hx-pointer" hx-get="{% url 'posts:title' id=post.id %}">
            {{ post.post|linebreaks }} <span class="text-primary"><small>{% trans "< less" %}&nbsp;|&nbsp;</small></span>
        </div>
    </div>
    <div class="my-3">
        {% if files %}
            <i class="bi bi-paperclip h5 text-secondary me-2">></i>
            {% for file in files %}
            <a class="badge text-bg-{{file.color}} nav-link" href="{{path}}{{file.file}}" target="_blank">{{file.shortName}}</a>
            {% endfor %}
        {% endif %}
    </div>
</div>

mateapp-crm/templates/posts/partials/post_title.html
{% load i18n %}

<div class="row justify-content-start" id="post" hx-swap="outerHTML swap:0.2s" hx-target="this">
    <div class="col py-1 col-lg-10">
        <span><i class="bi bi-pencil-square text-success h5 hx-pointer me-2" hx-get="{% url 'posts:edit' id=post.id %}"></i></span>{{ post.post_title }} 
        <span class="hx-pointer text-primary" hx-get="{% url 'posts:post' id=post.id %}"><small>&nbsp;|&nbsp;{% trans "more >" %}</small></span>
    </div>
</div>

mateapp-crm/templates/posts/partials/posts_list.html
{% load i18n %}
<!--target div for the list partial -->
<div id="list">
    <!--target div for the create partial -->
    <div id="create"></div>

    {% if page_obj %}
    {% for post in page_obj  %}

    <!--This div contains the card list page for infinite scrolling -->
    {% if forloop.last %}
        {% if  page_obj.number < page_obj.paginator.num_pages %}
            <div hx-get="{% url 'posts:list' %}?page={{ page_obj.number|add:1 }}" hx-trigger="revealed" hx-swap="afterend" hx-target="this">
        {% endif %}
    {% else %}
    <div>
    {% endif %}

        <!--Card-->
        <div class="row mt-2 justify-content-md-center" id="card_{{post.id}}" hx-target="this" hx-swap="outerHTML swap:0.2s">
            <div class="col col-lg-10 p-3 mx-1 border rounded bg-white">
                <div class="row row row-col-2 px-3 justify-content-start">
                    <div class="col col-10 col-lg-8 px-3 pt-1">
                        {% if post.company.companyName %}
                        <strong><a class="nav-link" href="/directory/company/{{ post.company.id }}/0/5">{{ post.company.companyName }}</a></strong>
                        {% else %}
                        <strong><a class="nav-link" href="/directory/person/{{ post.person.id }}">{{ post.person.firstName }}
                        {{ post.person.lastName }}</a></strong>
                        {{ post.person.company.companyName }}
                        {% endif %}
                        <!-- Placeholder para los partials de htmx -->
                        <div class="my-3">
                            {% include 'posts/partials/post_title.html' %}
                        </div>
                    </div>
                    <div class="col col-10 col-lg-4 pt-1 light-border-lg">
                        <div>
                            <small>{% trans "Created on " %}{{ post.date }}{% trans " by " %}{{ post.user.first_name }} {{ post.user.last_name }}.</small>
                        </div>                        
                        <div class="ms-3 my-2">
                            <span class="me-4" hx-delete="{% url 'posts:delete' id=post.id %}"><i class="bi bi-trash h5 hx-pointer text-secondary"></i></span>
                            <span id="upload_{{post.id}}">{% include 'posts/partials/files.html' %}</span>
                            </span>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>

mateapp-crm/templates/posts/partials/upload.html
{% load i18n %}
<form class="m-2" hx-post="{% url 'posts:upload' id=post.id %}" hx-target="#upload_{{post.id}}" hx-swap="outerHTML swap:0.2s" id="upload_{{post.id}}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="my-3">
        {{ uploadfileform.file }}
    </div>
    <div class="col col-lg-10 d-flex mb-3 justify-content-center">
        <progress id="progress_{{post.id}}" value='0' max='100'></progress>
    </div>
    <div class="col col-lg-10 d-flex justify-content-center">
        <button class="btn btn-outline-success btn-sm px-4 me-2" id="upload_button_{{post.id}}" type="submit" value="upload">{% trans "Upload" %}</button>
        <button class="btn btn-outline-secondary btn-sm px-4 mx-2" type="button" hx-get="{% url 'posts:files' id=post.id %}" onclick="htmx.trigger('#upload_{{post.id}}', 'htmx:abort')">{% trans "Cancel" %}</button>
    </div>      
</form>

<script>
    var progress_{{post.id}} = document.getElementById("progress_{{post.id}}");
    var button_{{post.id}} = document.getElementById("upload_button_{{post.id}}");
    var file = document.getElementById("id_file");
    
    progress_{{post.id}}.style.display = 'none';
    button_{{post.id}}.setAttribute('disabled', '');
    button_{{post.id}}.addEventListener("click", showProgress);
    file.addEventListener("change", checkSize);

    function checkSize() {
        
        let filesSize = 0;
        for (let i=0; i < this.files.length; i++) {
            filesSize = filesSize + this.files[i].size
        };

        if (filesSize > {{upload_max_size}} ) {
            alert('{% trans "Maximun upload size is 20MB!" %}');
            button_{{post.id}}.setAttribute('disabled', '');
        } else {
            button_{{post.id}}.removeAttribute('disabled');
        };
    };

    function showProgress() {
        progress_{{post.id}}.style.display = 'block';
    };

    htmx.on('#upload_{{post.id}}', 'htmx:xhr:progress', function(evt) {
        htmx.find('#progress_{{post.id}}').setAttribute('value', evt.detail.loaded/evt.detail.total * 100)
    });
</script>