mateapp-crm/directory/urls.py
from django.urls import path, include
from .api import CompanyViewSet, AddressViewSet, PersonViewSet, LeadViewSet
from . import views
from rest_framework import routers

app_name = 'directory'

router = routers.DefaultRouter()
router.register(r'companies', CompanyViewSet, 'companies')
router.register(r'address', AddressViewSet, 'address')
router.register(r'persons', PersonViewSet, 'persons')
router.register(r'leads', LeadViewSet, 'leads')

urlpatterns = [
    path('', views.index, name='Index'),
    # List
    path('persons/', views.persons, name='Persons'),
    path('companies/', views.companies, name='Companies'),
    path('person/<int:id>/', views.person, name='Person'),
    path('company/<int:id>/<int:a>/<int:b>/', views.company, name='Company'),
    # CUD Person
    path('create_person/', views.create_person, name='CreatePerson'),
    path('edit_person/<int:id>/', views.edit_person, name='EditPerson'),
    path('delete_person/<int:id>/', views.delete_person, name='DeletePerson'),
    path('restore_person/<int:id>/<int:u>/', views.restore_person, name='RestorePerson'),
    path('full_delete_person/<int:id>/', views.full_delete_person, name='FullDeletePerson'),
    path('person_notes/<int:id>/', views.personNotes, name='personNotes'),
    path('person_notes_title/<int:id>/', views.personNotesTitle, name='personNotesTitle'),
    path('edit_person_notes/<int:id>/', views.personNotesEdit, name='personNotesEdit'),
    path('create_person_post/<int:id>/', views.personPostCreate, name='personPostCreate'),
    path('person_sticky/<int:id>/<int:pid>/', views.person_sticky, name='personSticky'),
    #  CUD Company
    path('create_company/', views.create_company, name='CreateCompany'),
    path('edit_company/<int:id>/', views.edit_company, name='EditCompany'),
    path('delete_company/<int:id>/', views.delete_company, name='DeleteCompany'),
    path('restore_company/<int:id>/<int:u>/', views.restore_company, name='RestoreCompany'),
    path('full_delete_company/<int:id>/', views.full_delete_company, name='FullDeleteCompany'),
    path('company_notes/<int:id>/', views.companyNotes, name='companyNotes'),
    path('company_notes_title/<int:id>/', views.companyNotesTitle, name='companyNotesTitle'),
    path('edit_company_notes/<int:id>/', views.companyNotesEdit, name='companyNotesEdit'),
    path('company_persons_list/<int:id>/<int:a>/<int:b>/', views.companyPersons, name='companyPersons'),
    path('company_persons_collapsed/<int:id>/', views.companyPersonsCollapsed, name=('companyPersonsCollapsed')),
    path('create_company_post/<int:id>/', views.companyPostCreate, name='companyPostCreate'),
    path('company_sticky/<int:id>/<int:cid>/', views.company_sticky, name='companySticky'),
    # Favorites
    path('link_fav/<str:obj>/<int:oid>/', views.link_favorite, name='LinkFav'),
    path('unlink_fav/<int:lid>/', views.unlink_favorite, name='UnLinkFav'),
    path('favs/', views.favs, name='Favs'),
    path('unlink_fav_favs/<int:lid>/', views.unlink_favorite_favs, name='UnLinkFavFavs'),
    #  API
    path('api/', include(router.urls))
]

mateapp-crm/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('search/', views.search, name='search'),
    path('login/', views.login, name='login'),
    path('signout/', views.signout, name='Logout'),
    path('user_trash/<int:a>/<int:b>/', views.user_trash, name='User_Trash'),
    path('admin_trash/<int:a>/<int:b>/', views.admin_trash, name='Admin_Trash'),
    path('admin_home/<int:a>/<int:b>/', views.admin_home, name='Admin_Home'),
    path('backup/', views.do_backup, name='Backup'),
]

mateapp-crm/directory/models.py
from django.db import models
from django.conf import settings
from datetime import date

class BaseModel(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(blank=True, default=0)
    deletedBy = models.BigIntegerField(blank=True, null=True)
    
    class Meta:
        abstract = True

class Address(BaseModel):
    street = models.CharField(max_length=200, blank=True)
    postalCode = models.CharField(max_length=7, blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f'{self.street}, {self.city}'

class Company(BaseModel):
    companyName = models.CharField(max_length=100, blank=True)
    tax_id = models.CharField(max_length=15, blank=True)
    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING, blank=True, null=True)
    website = models.CharField(max_length=100, blank=True)
    companyPhone = models.CharField(max_length=25, blank=True)
    companyNotes = models.TextField(max_length=2000, blank=True)
    companyNotes_title = models.CharField(max_length=200, blank=True, null=True)

    def title(self):
        fline = self.companyNotes.split('\n', 1)[0]
        if len(fline) > 25:
            fline = fline[:25]
            title = f'{fline}...'
        else:
            title = fline
        return title

    def save(self, *args, **kwargs):
        self.companyNotes_title = self.title()
        super(Company, self).save(*args, **kwargs)

    def __str__(self):
        return self.companyName


class Person(BaseModel):
    lastName = models.CharField(max_length=50, blank=True)
    firstName = models.CharField(max_length=50, blank=True)
    celphone = models.CharField(max_length=25, blank=True)
    workphone = models.CharField(max_length=25, blank=True)
    email = models.CharField(max_length=100, blank=True)
    position = models.CharField(max_length=50, blank=True)
    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING, blank=True, null=True)
    notes = models.TextField(max_length=2000, blank=True)
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING, blank=True, null=True)
    notes_title = models.CharField(max_length=200, blank=True, null=True)

    def title(self):
        fline = self.notes.split('\n', 1)[0]
        if len(fline) > 25:
            fline = fline[:25]
            title = f'{fline}...'
        else:
            title = fline
        return title

    def save(self, *args, **kwargs):
        self.notes_title = self.title()
        super(Person, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.lastName}, {self.firstName}'


class Favorite(BaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, blank=True, null=True)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING, blank=True, null=True)
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING, blank=True, null=True)

class Lead(BaseModel):
    firstName = models.CharField(max_length=100, blank=True)
    lastName = models.CharField(max_length=100, blank=True)
    email = models.EmailField(unique=False)
    message = models.CharField(max_length=500, blank=True)
    messageDate = models.DateField(blank=True, null=True, default=date.today)

    def __str__(self):
        return f'{self.lastName} - {self.messageDate}'

mateapp-crm/directory/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, response, request, QueryDict
from django.template import loader
from django.contrib import messages
from django.db.models.functions import TruncDate
from django.contrib.auth import get_user_model
from django.db.models import Q, Value, Count, Min
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse_lazy
from .models import Address, Company, Person, Favorite
from posts.models import Post
from main.functions import paginator
from main.forms import SearchForm
from posts.forms import PostCreationForm
from .forms import PersonForm, CompanyForm, AddressFrom, PersonNotesForm, CompanyNotesForm
import copy
from itertools import chain
from operator import attrgetter
from django.conf import settings


########
# MAIN #
########

# Index

@login_required
def index(response):
    return redirect('/directory/persons/0/10/')


##############
# READ Views #
##############

# Fav List

@login_required
def favs(request):
    uid = request.user.id
    user = get_user_model().objects.get(id=uid)
    person_list = Person.objects.filter(Q(favorite__user=user, deleted=False)).annotate(entity=Value('lastName')).annotate(is_person=Value(True)).annotate(fav_id=Min('favorite__id', filter=Q(favorite__user=user)))
    companies_list = Company.objects.filter(Q(favorite__user=user, deleted=False)).annotate(entity=Value('companyName')).annotate(is_person=Value(False)).annotate(fav_id=Min('favorite__id', filter=Q(favorite__user=user)))
    fav_list = sorted(chain(person_list, companies_list),
                      key=attrgetter('entity'),
                      reverse=False,
                      )
    context = {
        'fav_list' : fav_list,
    }
    return render(request, 'directory/favs.html', context)

# Persons List

@login_required
def persons(request):
    uid = request.user.id
    user = get_user_model().objects.get(id=uid)
    searchform = SearchForm(request.GET)
    if searchform.is_valid():
        q = searchform.cleaned_data['q']
    else:
        q = None
    if q:
        ln_list = Person.objects.filter(lastName__icontains=q, deleted=False).annotate(fav=Count('favorite__user', filter=Q(favorite__user=user)))
        fn_list = Person.objects.filter(firstName__icontains=q, deleted=False).annotate(fav=Count('favorite__user', filter=Q(favorite__user=user)))
        cn_list = Person.objects.filter(company__companyName__icontains=q, deleted=False).annotate(fav=Count('favorite__user', filter=Q(favorite__user=user)))
        person_list = sorted(chain(ln_list, fn_list, cn_list),
                            key=attrgetter('lastName'),
                            )
        if not person_list:
            messages.warning(request, _("The search didn't return any result."))
    else:
        person_list = Person.objects.order_by('lastName').select_related('company').filter(deleted=False).annotate(fav=Count('favorite__user', filter=Q(favorite__user=user)))
        q = ''
    
    
    paginator = Paginator(person_list, settings.MAIN_PAGE_LENGTH)
    page = request.GET.get('page')
    try:
        persons = paginator.page(page)
    except PageNotAnInteger:
        persons = paginator.page(1)
    except EmptyPage:
        persons = paginator.page(paginator.num_pages)

    template = loader.get_template('directory/persons.html')

    context = {
        'person_list': persons,
        'searchform' : searchform,
        'q' : q
    }
    return HttpResponse(template.render(context, request))

# Companies List

@login_required
def companies(request):
    uid = request.user.id
    user = get_user_model().objects.get(pk=uid)
    searchform = SearchForm(request.GET)
    if searchform.is_valid():
            q = searchform.cleaned_data['q']
    else:
        q = None
    if q:
        companies_list = Company.objects.filter(companyName__icontains=q, deleted=False).annotate(fav=Count('favorite__user', filter=Q(favorite__user=user))) 
        if not companies_list:
            messages.warning(request, _("The search didn't return any result."))

    else:
        companies_list = Company.objects.order_by('companyName').select_related('address').filter(deleted=False).annotate(fav=Count('favorite__user', filter=Q(favorite__user=user)))
        q = ''
        
    
    paginator = Paginator(companies_list, settings.MAIN_PAGE_LENGTH)
    page = request.GET.get('page')
    try:
        companies = paginator.page(page)
    except PageNotAnInteger:
        companies = paginator.page(1)
    except EmptyPage:
        companies = paginator.page(paginator.num_pages)
    template = loader.get_template('directory/companies.html')

    context = {
        'companies_list': companies,
        'searchform' : searchform,
        'q' : q,
    }
    return HttpResponse(template.render(context, request))

# Person View

@login_required
def person(request, id):
    uid = request.user.id
    person = Person.objects.get(id=id)
    posts_list = Post.objects.filter(person=person, deleted=False).order_by('-action', '-modified_date').annotate(date=TruncDate('create_date'))
    paginator = Paginator(posts_list, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    try:
        fav = Favorite.objects.get(user = uid, person=person.id)
    except:
        fav = False
    if request.htmx:
        template = loader.get_template('directory/partials/person_posts_list.html')
    else:
        template = loader.get_template('directory/person.html')
    context = {
        'person' : person,
        'fav' : fav,
        'page_obj' : page_obj,
    }
    return HttpResponse(template.render(context, request))

# Company View

@login_required
def company(request, id, a, b):
    uid = request.user.id
    company = Company.objects.get(id=id)
    posts_list = Post.objects.filter(Q(company=company) | Q(person__company=company)).filter(deleted=False).order_by('-action', '-modified_date').annotate(date=TruncDate('create_date'))
    paginator = Paginator(posts_list, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    try:
        fav = Favorite.objects.get(user = uid, company=company.id)
    except:
        fav = False
    person_list = Person.objects.filter(company_id=id).filter(deleted=False)
    if request.htmx:
        template = loader.get_template('directory/partials/company_posts_list.html')
    else:
        template = loader.get_template('directory/company.html')
    context = {
        'company' : company,
        'fav' : fav,
        'person_list' : person_list,
        'page_obj' : page_obj,
    }
    return HttpResponse(template.render(context, request))



################################
# CREATE, UPDATE, DELETE Views #
################################

# Person Create

@login_required
def create_person(request):
    if request.method == 'POST':
        if '100' in request.POST:
            personform = PersonForm(request.POST)
            addressform = AddressFrom(request.POST)
            companyform = CompanyForm(request.POST)
            if personform.is_valid():
                person = personform.save()
                id = person.id
                return HttpResponseRedirect(f'/directory/person/{id}/')
        
        elif '110' in request.POST:
            personform = PersonForm(request.POST)
            addressform = AddressFrom(request.POST)
            companyform = CompanyForm(request.POST) 
            if personform.is_valid() and addressform.is_valid():
                address = addressform.save()
                person = personform.save(commit=False)
                person.address = address
                person.save()
                id = person.id
                return HttpResponseRedirect(f'/directory/person/{id}/')

        elif '111' in request.POST:
            personform = PersonForm(request.POST)
            addressform = AddressFrom(request.POST)
            companyform = CompanyForm(request.POST)
            if personform.is_valid() and addressform.is_valid():
                address = addressform.save()
                personform.save(commit=False)
                person.address = address
                person.save()
                id = person.id
                return HttpResponseRedirect(f'/directory/person/{id}/')


        elif '112' in request.POST:
            personform = PersonForm(request.POST)
            addressform = AddressFrom(request.POST)
            companyform = CompanyForm(request.POST)
            if personform.is_valid() and addressform.is_valid() and companyform.is_valid():
                addressform_company = copy.deepcopy(addressform)
                paddress = addressform.save()
                caddress = addressform_company.save()
                person = personform.save(commit=False)
                company = companyform.save(commit=False)
                
                company.address = caddress
                company.save()

                person.company = company
                person.address = paddress
                person.save()
                pid = person.id

                return HttpResponseRedirect(f'/directory/person/{pid}/')
        
        elif '102' in request.POST:
            personform = PersonForm(request.POST)
            addressform = AddressFrom(request.POST)
            companyform = CompanyForm(request.POST)
            if personform.is_valid() and companyform.is_valid():
                person = personform.save(commit=False)
                company = companyform.save()

                person.company = company
                person.save()
                pid = person.id
                return HttpResponseRedirect(f'/directory/person/{pid}/')

    else:
        companyform = CompanyForm()

mateapp-crm/templates/directory/company.html
{% extends 'main/base.html' %}
{% load i18n %}

{% block navbar %}
{% include 'includes/navbar.html' %}
{% endblock navbar %}

{% block content %}

<!-- Header -->
<div class="row py-3 justify-content-center" id="company">
    <div class="col col-lg-10 p-3 px-5 mx-1 rounded border bg-white">
        <h2>{{company.companyName}}
            {% if fav %}
            <span class="px-2" hx-get="/directory/unlink_fav/{{ fav.id }}/" hx-swap="outerHTML"><i class="bi bi-star-fill h5 hx-pointer text-warning"></i></span>
            {% else %}
            <span class="px-2" hx-get="/directory/link_fav/company_obj/{{ company.id }}/" hx-swap="outerHTML"><i class="bi bi-star h5 hx-pointer text-warning"></i></span>
            {% endif %}
        </h2>
        <hr class="separator">
        
        <div class="row row-col-2 justify-content-start">
            <div class="col col-10 col-md-6 py-1">
                <p class="mb-2"><small>{% trans "DATA:" %}</small></p>
                <div class="ps-1">
                    <h6>{{company.companyPhone}}</h6>
                    <h6><a class="nav-link" target="_blank" href="http://{{company.website}}">{{company.website}}</a></h6>
                    <h6>{{company.tax_id}}</h6>
                </div>
            </div>
            <div class="col col-10 col-md-6 py-1 light-border">
                <p class="mb-2"><small>{% trans "ADDRESS:" %}</small></p>
                <div class="ps-1">
                    <h6>{{company.address.street}}</h6>
                    <h6>{{company.address.postalCode}}</h6>
                    <h6>{{company.address.city}}</h6>
                    <h6>{{company.address.state}}</h6>
                    <h6>{{company.address.country}}</h6>
                </div>
                <div class="row pt-3 justify-content-center">
                    <div class="col col-lg-10 d-flex justify-content-center">       
                        <p><a href="{% url 'directory:EditCompany' id=company.id %}" class="btn btn-outline-success btn-sm px-4 mx-3" role="button">{% trans "Edit" %}</a></p>
                        {% comment %} <p><a href="{% url 'directory:Companies' a=0 b=10 %}" class="btn btn-outline-secondary btn-sm px-4 mx-3" role="button">{% trans "Back" %}</a></p> {% endcomment %}
                        {% if not person_list %}
                        <p><a href="{% url 'directory:DeleteCompany' id=company.id %}" class="btn btn-outline-danger btn-sm px-4 mx-3" role="button">{% trans "Delete" %}</a></p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="my-3">
            {% include 'directory/partials/company_notes_title.html' %}
        </div>
        
        {% if person_list %}
        <!-- Tabla -->
        <div class="row justify-content-center">
            <div class="col p-3">  
                <div id="persons_list">
                {% include 'directory/partials/company_persons_collapsed.html' %}
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>

<div class="row mt-3 justify-content-md-center">
    <div class="col col-lg-10 p-3 mx-1 rounded border bg-white">
        <div class="container-fluid px-4">
            <span class="h4"><i class="bi bi-stickies"></i>&nbsp;{% trans "Posts" %}</span>
            <span class="ms-3 mb-2 btn btn-outline-secondary btn-sm" hx-get="{% url 'directory:companyPostCreate' id=company.id %}" hx-target="#create" hx-swap="outerHTML swap:0.2s"><i class="bi bi-plus-square"></i>&nbsp;{% trans "Add Post" %}</span>
        </div>
    </div>
</div>

{% include 'directory/partials/company_posts_list.html' %}

{% endblock %}

mateapp-crm/templates/directory/create_company.html
{% extends 'main/base.html' %}
{% load static %}

{% block navbar %}
{% include 'includes/navbar.html' %}
{% endblock navbar %}

{% load i18n %}

{% block content %}

<form action="" method="post">

{% csrf_token %}

<div class="row py-3 justify-content-center">
    <div class="col col-lg-10 rounded border bg-white p-3 mx-1 col-lg-10">
        {% if title %}
        <div class="h2 px-4 py-2">{{title}}</div>
        {% else %}
        <div class="h2 px-4 py-2">{{company.companyName}}</div>
        {% endif %}

        <div class="row row-col-2 py-3 justify-content-center">
            <div class="col col-10 col-md-6 py-1">

                <div class="form-floating my-3 mx-2">
                   {{companyform.companyName}}
                    <label for="id_company">{% trans "Company Name:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{companyform.tax_id}}
                    <label for="id_tax_id">{% trans "Tax ID:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{companyform.website}}
                    <label for="id_website">{% trans "Website:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{companyform.companyPhone}}
                    <label for="id_companyphone">{% trans "Company Phone:" %}</label>
                </div>

            </div>

            <div class="col col-10 col-md-6 py-1 light-border">

                <div class="form-floating my-3 mx-2">
                    {{addressform.street}}
                    <label for="id_street">{% trans "Street:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{addressform.city}}
                    <label for="id_city">{% trans "City:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{addressform.state}}
                    <label for="id_state">{% trans "State:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{addressform.country}}
                    <label for="id_country">{% trans "Country:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{addressform.postalCode}}
                    <label for="id_postalecode">{% trans "Postal Code:" %}</label>
                </div>

                <div class="d-flex justify-content-center my-3 px-5 py-3">
                    <p><button type="submit" class="btn btn-outline-success px-3 mx-2">{% trans "Save" %}</button></p>
                    {% if company.id %}
                    <p><a href="/directory/company/{{ company.id }}/0/5/" class="btn btn-outline-secondary mx-2 px-4" role="button">{% trans "Cancel" %}</a></p>
                    {% else %}
                    <p><a href="/directory/companies/0/10/" class="btn btn-outline-secondary mx-2 px-4" role="button">{% trans "Cancel" %}</a></p>
                    {% endif %}
                </div>

            </div>
        </div>
        
        <div class="row py-3 justify-content-center">
            <div class="col p-3 mx-1">

                <div class="form-floating my-2">
                    {{companyform.companyNotes}}
                    <label for="id_company_notes">{% trans "Notes:" %}</label>
                </div>

            </div>
        </div>

    </div>
</div>
</form>

<script src="{% static 'directory/js/create_company_helper.js' %}"></script>
{% endblock %}

mateapp-crm/templates/directory/create_person.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}

{% block navbar %}
{% include 'includes/navbar.html' %}
{% endblock navbar %}

{% block content %}

<form action="" method="post">

{% csrf_token %}

<div class="row py-3 justify-content-center">
    <div class="col col-lg-10 rounded border bg-white p-3 mx-1 col-lg-10">
        {% if title %}
        <div class="h2 px-4 py-2">{{title}}</div>
        {% else %}
        <div class="h2 px-4 py-2">{{person.firstName}} {{person.lastName}}</div>
        {% endif %}

        <div class="row justify-content-start">
            <div class="col p-3 mx-1">
                <div class="row row-col-2 py-3 me-auto justify-content-between align-items-center">
                    
                    <div id="company_selector" class="col col-12 col-md-8"> 
                        <p>
                            <div>
                            {{personform.company}}
                            </div>
                        </p>
                    </div>
                    <div id="new_company_title" class="col col-12 col-md-8">
                        <p class="px-4">
                            <h4>{% trans "New Company" %}</h4>
                        </p>
                    </div>
                    {% if title %}
                    <div class="col col-6 col-md-3">
                        <p>
                            <div id="new_company" class="btn btn-outline-success btn-sm" onclick="toggle()">{% trans "Add Company" %}</div>
                        </p>
                    </div>
                    {% endif %}
                </div>
        
                <div id="company_form">
                <p>
                <div class="form-floating">
                    {{companyform.companyName}}
                    <label for="id_company">{% trans "Company Name:" %}</label>
                </div>
                </p>
                <p>
                <div class="form-floating">
                    {{companyform.tax_id}}
                    <label for="id_tax_id">{% trans "Tax ID:" %}</label>
                </div>
                </p>
                <p>
                    <div class="form-floating">
                        {{companyform.website}}
                        <label for="id_website">{% trans "Website:" %}</label>
                    </div>
                </p>
                <p>
                    <div class="form-floating">
                        {{companyform.companyPhone}}
                        <label for="id_companyphone">{% trans "Company Phone:" %}</label>
                    </div>
                </p>
                </div>
            </div>
        </div>

        <div class="row row-col-2 py-3 justify-content-center">
            <div class="col col-10 col-md-6 py-1">
  
                <div class="form-floating my-3 mx-2">
                   {{personform.firstName}}
                    <label for="id_firstname">{% trans "First Name:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{personform.lastName}}
                    <label for="id_lastname">{% trans "Last Name:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{personform.position}}
                    <label for="id_position">{% trans "Position:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{personform.celphone}}
                    <label for="id_celphone">{% trans "Cell Phone:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{personform.email}}
                    <label for="id_email">{% trans "eMail:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{personform.workphone}}
                    <label for="id_workphone" class="form-label">{% trans "Work Phone:" %}</label>
                </div>

            </div>
            <div class="col col-10 col-md-6 py-1 light-border">

                <div class="form-floating my-3 mx-2">
                    {{addressform.street}}
                    <label for="id_street">{% trans "Street:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{addressform.city}}
                    <label for="id_city">{% trans "City:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{addressform.state}}
                    <label for="id_state">{% trans "State" %}:</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{addressform.country}}
                    <label for="id_country">{% trans "Country:" %}</label>
                </div>

                <div class="form-floating my-3 mx-2">
                    {{addressform.postalCode}}
                    <label for="id_postalecode">{% trans "Postal Code:" %}</label>
                </div>

                <div class="d-flex justify-content-center my-3 py-3">
                    <p><button type="submit" id="save_button" name="100" value="100" class="btn btn-outline-success px-3 mx-3">{% trans "Save" %}</button></p>
                    {% if person.id %}
                    <p><a href="/directory/person/{{ person.id }}" class="btn btn-outline-secondary mx-3 px-4" role="button">{% trans "Cancel" %}</a></p>
                    {% else %}
                    <p><a href="/directory/persons/0/10/" class="btn btn-outline-secondary mx-3 px-4" role="button">{% trans "Cancel" %}</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
        
        <div class="row py-3 justify-content-center">
            <div class="col p-3 mx-1">
            <p>
                <div class="form-floating my-2">
                    {{personform.notes}}
                    <label for="id_notes">{% trans "Notes:" %}</label>
                </div>
                </p>
            </div>
        </div>

    </div>
</div>

<script src="{% static 'directory/js/create_person_helper.js' %}"></script>
{% endblock %}

mateapp-crm/templates/directory/new_web_lead.html
{% load i18n %}
{% autoescape off %}
{% trans "There is a new lead form the website contact form:" %}

{% trans "Name:" %} {{ firstName }} {{ lastName }}

{% trans "email:" %} {{ email }}

{% trans "Message:" %} {{ message }}

{% endautoescape %}